name: meet-v2
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-meet-v2-app
    container_name: meet-v2-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - v2-network

  web:
    image: nginx:alpine
    container_name: meet-v2-web
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - v2-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: meet-v2-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_v2
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - v2-network

  npm:
    image: node:20-alpine
    container_name: meet-v2-npm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: npm run dev
    networks:
      - v2-network
    ports:
      - "5173:5173"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: meet-v2-pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"
    networks:
      - v2-network
    depends_on:
      - db

networks:
  v2-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
